name: mobile_arquitetura_02
description: Aplicação Flutter com arquitetura em camadas, cache, tratamento de erros e gerenciamento de estado (Atividade 05).

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
